-- RUN THIS PORTION IN YOUR SUPABASE SQL EDITOR FIRST

-- Add request_type and share_code columns to question_requests if they do not exist
ALTER TABLE public.question_requests 
ADD COLUMN IF NOT EXISTS request_type TEXT DEFAULT 'assessment',
ADD COLUMN IF NOT EXISTS share_code TEXT;

-- Let's make sure the table exists and columns are correct
COMMENT ON COLUMN public.question_requests.request_type IS 'The type of resource requested: assessment, assignment, or groupwork';
COMMENT ON COLUMN public.question_requests.share_code IS 'The unique code generated by the admin upon completing the request';
